#model
classes: 4
dropout: 0.1
encoder_name: resnext101_32x48d
encoder_weights: instagram

# # crop size
# height: 256
# width: 416

# dataloader
batch_size: 1
data_folder: ./data/
df_path: ./data/train.csv
nworkers: 4
validation_split: 0.2

# optimizer
lr: 7.0e-05
weight_decay: 3.0e-05

# training:
num_epochs: 20
tensorboard: true
